import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { ToastContainer, toast } from 'react-toastify'
import api from './services/api'
import './App.css'

const expenseCategories = ['Food', 'Travel', 'Shopping', 'Bills', 'Education', 'Entertainment', 'Healthcare', 'Rent', 'Other']
const incomeCategories = ['Salary', 'Freelance', 'Business', 'Investment', 'Bonus', 'Other']
const seedExpenses = [{ id: 1, title: 'Whole Foods Market', amount: 84.32, category: 'Food', date: '2024-05-24', paymentMethod: 'Card' }]
const seedIncome = [{ id: 2, source: 'Salary deposit', amount: 4200, category: 'Salary', date: '2024-05-23' }]
const seedBudgets = [{ id: 3, category: 'Food', amount: 600 }]
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const notify = (message) => toast.success(message)
const normalizeExpense = (item) => ({ ...item, paymentMethod: item.paymentMethod || item.payment_method || 'Card', amount: Number(item.amount) })
const getCategorySpend = (expenses, category) => expenses
  .filter((expense) => (expense.category || '').toLowerCase() === String(category || '').toLowerCase())
  .reduce((sum, expense) => sum + Number(expense.amount || 0), 0)

function Icon({ name, size = 20 }) {
  const paths = { home: 'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1V10Z', card: 'M3 6h18v13H3z M3 10h18', chart: 'M4 19V9m5 10V5m5 14v-7m5 7V3', wallet: 'M3 6h18v14H3z M3 6l2-3h15v3 M16 13h5', user: 'M20 21a8 8 0 0 0-16 0M12 11a4 4 0 1 0-8 0 4 4 0 0 0 8 0Z', logout: 'M10 17l5-5-5-5m5 5H3m8-8V3h10v18H11v-4', bell: 'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4', search: 'm20 20-4-4m2-5a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z', plus: 'M12 5v14M5 12h14' }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name] || paths.home} /></svg>
}

function Auth({ onLogin }) {
  const [mode, setMode] = useState('register')
  const { register: field, handleSubmit, reset, formState: { errors } } = useForm()
  const submit = async (form) => {
    try {
      const { data } = await api.post(mode === 'register' ? '/auth/register' : '/auth/login', form)
      if (mode === 'register') { reset(); setMode('login'); notify('Account created. Please sign in.') } else { localStorage.setItem('spendwise_token', data.token); localStorage.setItem('spendwise_user', JSON.stringify(data.user)); onLogin(data.user); notify('Welcome back') }
    } catch (error) { toast.error(error.response?.data?.error || 'Could not connect to the API') }
  }
  const title = mode === 'register' ? 'Create your account' : 'Welcome back'
  return <div className="auth-page"><div className="auth-card"><div className="brand"><span className="brand-mark">S</span><span>Spend<span>Wise</span></span></div><div className="auth-heading"><p className="eyebrow">Personal finance, made clear</p><h1>{title}</h1><p>{mode === 'register' ? 'Register first to start managing your finances.' : mode === 'forgot' ? 'Enter your email to request a one-time reset code.' : mode === 'reset' ? 'Enter the code from the API terminal and choose a new password.' : 'Sign in to continue to your financial overview.'}</p></div><div className="or"><span>use your email</span></div><form onSubmit={handleSubmit(submit)}>{mode !== 'reset' && <label>Email address<input type="email" {...field('email', { required: 'Email is required' })} placeholder="you@example.com" />{errors.email && <small>{errors.email.message}</small>}</label>}{mode === 'register' && <label>Full name<input {...field('name', { required: 'Name is required' })} placeholder="Jordan Davis" />{errors.name && <small>{errors.name.message}</small>}</label>}{mode === 'login' && <label>Password<input type="password" {...field('password', { required: 'Password is required' })} placeholder="Your password" />{errors.password && <small>{errors.password.message}</small>}</label>}{mode === 'register' && <label>Password<input type="password" {...field('password', { required: 'Password is required', minLength: { value: 8, message: 'Use at least 8 characters' } })} placeholder="At least 8 characters" />{errors.password && <small>{errors.password.message}</small>}</label>}{mode === 'reset' && <><label>Email address<input type="email" {...field('email', { required: true })} placeholder="you@example.com" /></label><label>Reset code<input inputMode="numeric" {...field('code', { required: true, minLength: 6, maxLength: 6 })} placeholder="6-digit code" /></label><label>New password<input type="password" {...field('newPassword', { required: true, minLength: { value: 8, message: 'Use at least 8 characters' } })} placeholder="At least 8 characters" /></label></>}<button className="primary-button wide">{mode === 'register' ? 'Create account' : mode === 'login' ? 'Sign in' : mode === 'forgot' ? 'Send reset code' : 'Set new password'} <span>-&gt;</span></button></form>{mode === 'login' && <button className="forgot-link" type="button" onClick={() => { reset(); setMode('forgot') }}>Forgot password?</button>}<p className="auth-switch">{mode === 'register' ? 'Already have an account?' : 'Need an account?'} <button type="button" onClick={() => { reset(); setMode(mode === 'register' ? 'login' : 'register') }}>{mode === 'register' ? 'Sign in' : 'Register first'}</button></p>{(mode === 'forgot' || mode === 'reset') && <button className="back-link" type="button" onClick={() => { reset(); setMode('login') }}>Back to sign in</button>}</div></div>
}

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('spendwise_user') || 'null'))
  const [page, setPage] = useState('Overview')
  const [expenses, setExpenses] = useState([])
  const [income, setIncome] = useState([])
  const [budgets, setBudgets] = useState([])
  const [notifications, setNotifications] = useState([])

  useEffect(() => {
    if (!user) return
    Promise.all([api.get('/expenses'), api.get('/income'), api.get('/budgets')]).then(([expense, incomeResult, budget]) => {
      setExpenses(expense.data.map(normalizeExpense)); setIncome(incomeResult.data); setBudgets(budget.data)
    }).catch(() => { setExpenses(seedExpenses); setIncome(seedIncome); setBudgets(seedBudgets); toast.info('API unavailable; showing demo data') })
  }, [user])
  useEffect(() => {
    const profileChip = document.querySelector('.profile-chip')
    if (!profileChip) return undefined
    const openProfile = () => setPage('Profile')
    profileChip.addEventListener('click', openProfile)
    return () => profileChip.removeEventListener('click', openProfile)
  }, [user, page])
  useEffect(() => {
    const bell = document.querySelector('.top-actions .icon-button')
    if (!bell) return undefined
    bell.classList.add('notification-button')
    bell.setAttribute('aria-label', 'Notifications')
    let badge = bell.querySelector('.notification-count')
    if (notifications.length && !badge) { badge = document.createElement('b'); badge.className = 'notification-count'; bell.appendChild(badge) }
    if (badge) { badge.textContent = notifications.length > 99 ? '99+' : String(notifications.length); badge.hidden = notifications.length === 0 }
    const toggle = () => { let panel = document.querySelector('.notification-panel'); if (panel) { panel.remove(); return }; panel = document.createElement('div'); panel.className = 'notification-panel'; panel.innerHTML = `<div class="notification-header"><strong>Notifications</strong><button type="button">Mark all read</button></div>`; if (!notifications.length) panel.innerHTML += '<p class="notification-empty">No new notifications</p>'; notifications.forEach((item) => { panel.innerHTML += `<div class="notification-item"><span class="notification-dot"></span><div><strong>${item.message}</strong><small>${item.time}</small></div></div>` }); panel.querySelector('button').onclick = () => { setNotifications([]); panel.remove() }; bell.parentElement.appendChild(panel) }
    bell.addEventListener('click', toggle)
    return () => bell.removeEventListener('click', toggle)
  }, [notifications, user, page])
  if (!user) return <><Auth onLogin={setUser} /><ToastContainer position="bottom-right" hideProgressBar /></>
  const addNotification = (message) => setNotifications((items) => [{ id: Date.now(), message, time: 'Just now' }, ...items])
  const addExpense = async (item) => { const { data } = await api.post('/expenses', { ...item, amount: Number(item.amount), payment_method: item.paymentMethod }); setExpenses((items) => [...items, normalizeExpense(data)]); addNotification(`Expense added: ${item.title}`) }
  const addIncome = async (item) => { const { data } = await api.post('/income', { ...item, amount: Number(item.amount) }); setIncome((items) => [...items, data]); addNotification(`Income added: ${item.source}`) }
  const deleteTransaction = async (type, id) => { await api.delete(`/${type === 'Expense' ? 'expenses' : 'income'}/${id}`); type === 'Expense' ? setExpenses((items) => items.filter((item) => item.id !== id)) : setIncome((items) => items.filter((item) => item.id !== id)); addNotification(`${type} deleted`) }
  const addBudget = async (item) => { const { data } = await api.post('/budgets', { ...item, amount: Number(item.amount), month: new Date().toISOString().slice(0, 10) }); setBudgets((items) => [...items, data]); addNotification(`Budget added: ${item.category}`) }
  const deleteBudget = async (id) => { await api.delete(`/budgets/${id}`); setBudgets((items) => items.filter((item) => item.id !== id)); addNotification('Budget deleted') }
  const incomeTotal = income.reduce((sum, item) => sum + Number(item.amount), 0)
  const expenseTotal = expenses.reduce((sum, item) => sum + Number(item.amount), 0)
  const logout = () => { localStorage.clear(); setUser(null) }
  const nav = [{ label: 'Overview', icon: 'home' }, { label: 'Transactions', icon: 'card' }, { label: 'Analytics', icon: 'chart' }, { label: 'Budgets', icon: 'wallet' }, { label: 'Profile', icon: 'user' }]
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">S</span><span>Spend<span>Wise</span></span></div><div className="workspace"><div className="workspace-avatar">{initials(user.name)}</div><div><strong>{user.name}</strong><small>Personal workspace</small></div></div><nav>{nav.map((item) => <button key={item.label} className={`nav-item ${page === item.label ? 'active' : ''}`} onClick={() => setPage(item.label)}><Icon name={item.icon} size={19} />{item.label}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={logout}><Icon name="logout" size={19} />Sign out</button></div></aside><main className="main-content"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><span>&gt;</span><strong>{page}</strong></div><div className="top-actions"><button className="icon-button"><Icon name="bell" size={19} /></button><div className="profile-chip"><div className="profile-avatar">{initials(user.name)}</div><span>{user.name}</span></div></div></header>{page === 'Overview' && <Overview username={user.name} income={incomeTotal} expenses={expenses} budgets={budgets} transactions={[...income.map((x) => ({ ...x, title: x.source, amount: x.amount })), ...expenses.map((x) => ({ ...x, title: x.title, amount: -x.amount }))].sort((a, b) => new Date(b.date) - new Date(a.date))} onAdd={() => setPage('Transactions')} onIncome={() => setPage('Transactions')} />}{page === 'Transactions' && <Transactions expenses={expenses} income={income} onExpense={addExpense} onIncome={addIncome} onDelete={async (type, id) => { try { await deleteTransaction(type, id); notify('Transaction deleted') } catch { toast.error('Could not delete transaction') } }} />}{page === 'Analytics' && <Analytics income={incomeTotal} expenses={expenseTotal} />}{page === 'Budgets' && <Budgets budgets={budgets} expenses={expenses} onAdd={addBudget} onDelete={deleteBudget} />}{page === 'Profile' && <Profile user={user} onSave={async (name) => { const { data } = await api.put('/users/profile', { name, profileImage: user.profileImage }); localStorage.setItem('spendwise_user', JSON.stringify(data)); setUser(data); notify('Profile updated') }} />}</main><ToastContainer position="bottom-right" autoClose={2500} hideProgressBar /></div>
}
function initials(name = 'User') { return name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() }
function Heading({ title, subtitle, action, onAction, secondaryAction, onSecondaryAction, notificationButton }) { return <section className="page-heading"><div><p className="eyebrow">Friday, September 2, 2026</p><h1>{title}</h1><p className="subheading">{subtitle}</p></div><div className="heading-actions">{notificationButton}{secondaryAction && <button className="outline-button light" onClick={onSecondaryAction}>{secondaryAction}</button>}{action && <button className="primary-button" onClick={onAction}><Icon name="plus" size={18} />{action}</button>}</div></section> }
function Overview({ username, income, expenses, budgets, transactions, onIncome }) { const expenseTotal = expenses.reduce((sum, item) => sum + Number(item.amount), 0); return <><Heading title={`Hello, ${username}`} subtitle="Here's what's happening with your money." action="Add income" onAction={onIncome} secondaryAction="Update income" onSecondaryAction={onIncome} /><div className="stats-grid"><Stat title="Total balance" value={income - expenseTotal} icon="wallet" tone="blue" /><Stat title="Total income" value={income} icon="chart" tone="green" /><Stat title="Total expenses" value={expenseTotal} icon="card" tone="orange" /><Stat title="Remaining budget" value={budgets.reduce((sum, item) => sum + Number(item.amount), 0) - expenseTotal} icon="wallet" tone="purple" /></div><div className="feature-grid"><div className="panel feature-panel"><PanelTitle title="Recent transactions" subtitle="Your latest financial activity" />{transactions.length ? transactions.slice(0, 6).map((item) => <TransactionRow key={item.id} item={item} />) : <div className="empty-state">No transactions yet.</div>}</div><div className="panel feature-panel"><PanelTitle title="Budget health" subtitle="Monthly category limits" />{budgets.length ? budgets.map((item) => <BudgetRow key={item.id} item={item} spent={getCategorySpend(expenses, item.category)} />) : <div className="empty-state">Create your first budget.</div>}</div></div></> }
function Stat({ title, value, icon, tone }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon name={icon} size={19} /></div><p>{title}</p><h2>{money(value)}</h2><div className="stat-change"><span>Updated</span></div></div> }
function PanelTitle({ title, subtitle }) { return <div className="panel-header"><div><h2>{title}</h2><p>{subtitle}</p></div></div> }
function TransactionRow({ item, onDelete }) { return <div className="transaction-row"><div className="transaction-icon blue">{(item.title || '').slice(0, 2).toUpperCase()}</div><div className="transaction-info"><strong>{item.title}</strong><small>{item.category} - {item.date}</small></div><strong className={`amount ${item.amount > 0 ? 'positive' : ''}`}>{item.amount > 0 ? '+' : '-'}{money(Math.abs(item.amount))}</strong>{onDelete && <button className="row-delete" onClick={onDelete}>x</button>}</div> }
function Transactions({ expenses, income, onExpense, onIncome, onDelete }) { const [type, setType] = useState('Expense'); const [query, setQuery] = useState(''); const [showForm, setShowForm] = useState(false); const list = [...expenses.map((x) => ({ ...x, title: x.title, type: 'Expense', signed: -x.amount })), ...income.map((x) => ({ ...x, title: x.source, type: 'Income', signed: x.amount }))].filter((x) => x.title.toLowerCase().includes(query.toLowerCase())); const { register, handleSubmit, reset } = useForm(); const submit = (data) => { (type === 'Expense' ? onExpense : onIncome)(data).then(() => { reset(); setShowForm(false); notify(`${type} added`) }).catch(() => toast.error('Could not save transaction')) }; return <><Heading title="Transactions" subtitle="Track every movement of your money." action="Add transaction" onAction={() => setShowForm(!showForm)} />{showForm && <form className="panel inline-form" onSubmit={handleSubmit(submit)}><div className="form-tabs"><button type="button" className={type === 'Expense' ? 'selected' : ''} onClick={() => setType('Expense')}>Expense</button><button type="button" className={type === 'Income' ? 'selected' : ''} onClick={() => setType('Income')}>Income</button></div><label>{type === 'Expense' ? 'Title' : 'Source'}<input {...register(type === 'Expense' ? 'title' : 'source', { required: true })} /></label><label>Amount<input type="number" step="0.01" {...register('amount', { required: true })} /></label><label>Category<select {...register('category')}><option value="">Select category</option>{(type === 'Expense' ? expenseCategories : incomeCategories).map((x) => <option key={x}>{x}</option>)}</select></label><label>Date<input type="date" {...register('date', { required: true })} /></label>{type === 'Expense' && <label>Payment method<select {...register('paymentMethod')}><option>Card</option><option>Cash</option><option>Bank transfer</option></select></label>}<button className="primary-button">Save {type.toLowerCase()}</button></form>}<div className="panel table-panel"><div className="table-tools"><div className="search-box"><Icon name="search" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search transactions" /></div><span>{list.length} records</span></div><div className="table-head"><span>Date</span><span>Title / source</span><span>Category</span><span>Type</span><span>Amount</span><span>Action</span></div>{list.map((item) => <div className="table-row" key={`${item.type}-${item.id}`}><span>{item.date}</span><span><strong>{item.title}</strong></span><span>{item.category}</span><span><em className={item.type.toLowerCase()}>{item.type}</em></span><strong className={item.signed > 0 ? 'positive' : ''}>{item.signed > 0 ? '+' : '-'}{money(Math.abs(item.signed))}</strong><button className="row-delete" onClick={() => onDelete(item.type, item.id)}>Delete</button></div>)}</div></> }
function BudgetRow({ item, spent }) { const percent = item.amount > 0 ? Math.min(100, Math.round(spent / item.amount * 100)) : 0; return <div className="budget-row"><div><strong>{item.category}</strong><small>{money(spent)} of {money(item.amount)}</small></div><div className="progress-track"><span style={{ width: `${percent}%` }} /></div><b className={percent >= 90 ? 'warning' : ''}>{percent}%</b></div> }
function Budgets({ budgets, expenses, onAdd, onDelete }) { const { register, handleSubmit, reset } = useForm(); const submit = (data) => onAdd(data).then(() => { reset(); notify('Budget created') }).catch(() => toast.error('Could not create budget')); return <><Heading title="Budgets" subtitle="Give every rupee a direction." /><div className="budget-layout"><div className="panel"><PanelTitle title="Monthly category budgets" subtitle="Warnings appear when you are close to a limit." />{budgets.map((item) => <div className="budget-item" key={item.id}><BudgetRow item={item} spent={getCategorySpend(expenses, item.category)} /><button className="row-delete" onClick={() => onDelete(item.id).then(() => notify('Budget deleted')).catch(() => toast.error('Could not delete budget'))}>Delete</button></div>)}</div><form className="panel budget-form" onSubmit={handleSubmit(submit)}><PanelTitle title="Create budget" subtitle="Set a limit for this month." /><label>Category<select {...register('category', { required: true })}>{expenseCategories.map((x) => <option key={x}>{x}</option>)}</select></label><label>Budget amount<input type="number" step="0.01" {...register('amount', { required: true })} /></label><button className="primary-button">Create budget</button></form></div></> }
function Analytics({ income, expenses }) { return <><Heading title="Analytics" subtitle="Understand the habits behind your numbers." /><div className="stats-grid"><Stat title="Income" value={income} icon="chart" tone="green" /><Stat title="Expenses" value={expenses} icon="card" tone="orange" /><Stat title="Savings rate" value={income ? `${Math.round((income - expenses) / income * 100)}%` : '0%'} icon="wallet" tone="blue" /></div><div className="panel analytics-panel"><PanelTitle title="Income versus expenses" subtitle="Current totals from PostgreSQL" /><div className="analytics-bar"><span>Income</span><div><i style={{ width: '100%' }} /></div><strong>{money(income)}</strong></div><div className="analytics-bar"><span>Expenses</span><div><i style={{ width: `${income ? Math.min(100, expenses / income * 100) : 0}%` }} /></div><strong>{money(expenses)}</strong></div></div></> }
function Profile({ user, onSave }) { const { register, handleSubmit } = useForm({ defaultValues: { name: user.name } }); return <><Heading title="Profile" subtitle="Keep your account details up to date." /><form className="panel profile-form" onSubmit={handleSubmit((data) => onSave(data.name))}><div className="profile-large">{initials(user.name)}</div><label>Full name<input {...register('name', { required: true })} /></label><label>Email address<input value={user.email} disabled /></label><button className="primary-button">Save changes</button></form></> }

export default App
